### ISSUE TITLE
Feature request: make color scheme configurable

### ISSUE THREAD

**Issue by Goury** [unlimitedbacon/stl-thumb#10]
Would be nice to have an option to generate thumbnails of different color without recompiling this nice thing.

**Comment by unlimitedbacon** [comment]
Done. [See the README](https://github.com/unlimitedbacon/stl-thumb/blob/master/README.md#options) for the new command line options for customizing the colors. If you want custom colors in your file manager as well, you can edit the command in `/usr/share/thumbnailers/stl-thumb.thumbnailer`.

Also, for those on Windows stl-thumb now uses [the colors from your system theme](https://github.com/unlimitedbacon/stl-thumb/releases/tag/v0.3.1).

**Comment by Goury** [comment]
Noice!

**Comment by Hyperspeed1313** [comment]
Is there a way for stl-thumb to NOT use the system theme color in Windows? I'd much rather the previews use a neutral color than the bright blue I prefer for the system theme.

**Comment by unlimitedbacon** [comment]
At the moment theres no way to configure the options on Windows. I'm not sure what the best approach to this would be.
