### ISSUE TITLE
How to use command line?

### ISSUE THREAD

**Issue by garage100** [unlimitedbacon/stl-thumb#11]
Hi
Can you give an example to how change stl color preview to gray in windows 10?
thanks
yoav

**Comment by unlimitedbacon** [comment]
There is no way to do it system wide on Windows yet. I'm still trying to figure out how to make it configurable. However, if you want to generate a single image with custom colors, the command would look like this.

```
"C:\Program Files\stl-thumb\stl-thumb.exe" -m 222222 888888 ffffff 3DBenchy.stl benchy.png
```

There are 3 different colors needed. Ambient, diffuse, and specular. You can read more about what these mean here.
https://learnopengl.com/Lighting/Basic-Lighting

**Comment by unlimitedbacon** [comment]
On Windows, stl-thumb now uses your system theme colors.
https://github.com/unlimitedbacon/stl-thumb/releases/tag/v0.3.1
