### ISSUE TITLE
Custom work for 3D thumbnail plugin

### ISSUE THREAD

**Issue by JoshKlint** [unlimitedbacon/stl-thumb#17]
Hi, I am interested in having a thumbnail plugin for our own 3D file format implemented. The file format is very simple to load, and we have C++ code that can load it into memory. I was wondering if you would be available to work on this, later this year?

**Comment by unlimitedbacon** [comment]
Yes, I might be able to do that. Please email me directly at unlimitedbacon@gmail.com.
