### ISSUE TITLE
DEB Build for x86_64

### ISSUE THREAD

**Issue by thetrebor** [unlimitedbacon/stl-thumb#20]
I tried to build from source on my Synology NAS but I'm running into linker errors and it looks like it's just not going to fly (at least with my skill level with build systems, gcc, and rust).  

**Would it be possible for you to roll an x86_64 GNU/Linux  version and add it to the packages?** 

Failing that do you know of a place where I can diagnose:  "error: linker `cc` not found"
gcc is installed and available, but when I symlink cc to gcc the cargo build step fails differently.  I suspect there's just some essential build tools that aren't available on the NAS

Greatly appreciate your help.  This tool was great and I bought a NAS specifically to make use of it, and then realized too late it was the x86 version and not the ARM version (facepalm)

**Comment by unlimitedbacon** [comment]
There already is an x86_64 build.
https://github.com/unlimitedbacon/stl-thumb/releases/download/v0.3.1/stl-thumb_0.3.1_amd64.deb

Does that one not work?

**Comment by thetrebor** [comment]
You are a scholar and a gentleman.  I was apparently fully insane and
missed that link.
Thank you.
