### ISSUE TITLE
Installer source?

### ISSUE THREAD

**Issue by Leadwerks** [unlimitedbacon/stl-thumb#21]
Is the source for the installer available somewhere? I am interested in creating an installer for another image thumbnail previewer. Thank you.

**Comment by unlimitedbacon** [comment]
https://github.com/unlimitedbacon/STLThumbWindows

**Comment by nathanielstenzel** [comment]
What about the Linux installer?

**Comment by unlimitedbacon** [comment]
Which distro? For debian packages I use [cargo-deb](https://github.com/mmstick/cargo-deb). For Arch, the [`PKGBUILD`](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=stl-thumb) script can be found in the AUR.
