### ISSUE TITLE
support stream in and out

### ISSUE THREAD

**Issue by Dogm** [unlimitedbacon/stl-thumb#23]
It possible for stream stl as standart input, not as file?

**Comment by unlimitedbacon** [comment]
Not right now, but this shouldn't be too hard to add.

**Comment by Dogm** [comment]
Can you implement this logic in next versions?

**Comment by unlimitedbacon** [comment]
Added in https://github.com/unlimitedbacon/stl-thumb/commit/4b6011553de51db22fdb4418fe282dc466d7d40d
