### ISSUE TITLE
AWS compatibility problem

### ISSUE THREAD

**Issue by Dogm** [unlimitedbacon/stl-thumb#24]
Hi, i try use this project for generate thumbnails on win10 VPS
Have next problem

![image](https://user-images.githubusercontent.com/13658104/90337327-7797cd80-dfea-11ea-99cd-f9e5d7df6da7.png)
![image](https://user-images.githubusercontent.com/13658104/90337337-854d5300-dfea-11ea-8d31-e96e61091498.png)

Seem so they have OpenGL 1.1.0 version
Shaders in src have 120 version

It possible make support for 110 version of OpenGL?

**Comment by unlimitedbacon** [comment]
Sorry, this is not going to be possible. We require at least OpenGL 2.1 / GLSL 1.20 (that's the version you see in the shader files). OpenGL 1 was a completely different way of doing things, and has been obsolete for decades. For all intents and purposes, your system does not support OpenGL.
