### ISSUE TITLE
[enhancement request] Create local image files in Windows

### ISSUE THREAD

**Issue by Aevaris** [unlimitedbacon/stl-thumb#26]
Hi there,

It'd be great if there was a command line option for Windows to point this at a directory and create png/jpg/etc files for each STL.

**Comment by unlimitedbacon** [comment]
I might add an option for processing many STLs at once at some point. In the mean time, it shouldn't be too hard to batch script to do it.

**Comment by Aevaris** [comment]
Is there a way to do a single file in Windows? I only saw command line commands for Linux.

**Comment by unlimitedbacon** [comment]
The same options work on Windows. You just need to run stl-thumb.exe from the program files folder.

**Comment by Aevaris** [comment]
Ah, my bad. This is really cool! Any way to change the light location? I've been looking for a quick tool to ideally take images of my STLs. It's slow work to open each in meshmixer, position, take a picture, and then rename the picture. This does all of that in one command.

**Comment by unlimitedbacon** [comment]
The light direction is fixed at the moment. I'll add that to the wishlist, though.

**Comment by Aevaris** [comment]
Cool, thanks for your help and putting this together!
