### ISSUE TITLE
Unistall ?

### ISSUE THREAD

**Issue by picpic2b** [unlimitedbacon/stl-thumb#28]
Hello , i have unistalled the software but thumbnail still here ?

**Comment by unlimitedbacon** [comment]
I assume you are talking about Windows? Uninstalling does not delete the thumbnail cache. You can do this manually using the [Disk Cleanup](https://en.wikipedia.org/wiki/Disk_Cleanup) utility.

**Comment by picpic2b** [comment]
yes windows , i did :s , still here
