### ISSUE TITLE
Support Opengl 2.1 / GLSL 1.20

### ISSUE THREAD

**Issue by rebeltaz** [unlimitedbacon/stl-thumb#3]
After installing this on a 64-bit Ubuntu 16.04 with the MATE 1.12.1 desktop environment and the Nemo 3.6.5 file browser set as default, the thumbnails show up as text document icons instead of graphical representations of the STL files. In Nemo's settings, I Preview File Size is set to 'under 5mb', but I also tried raising that to 'under 10mb'.

**Comment by unlimitedbacon** [comment]
First lets make sure that Nemo is correctly identifying the STL files. Right click on one and go to properties. What does it say the type is? It should be `model/stl`.

**Comment by rebeltaz** [comment]
For some reason, I got a crash report from Ubuntu saying that this app (program) crashed. I couldn't find anyway to select the text of that. Would a log have been created with these details?

**Comment by unlimitedbacon** [comment]
Hmmm. Can you try running stl-thumb independently? Do this.
```
stl-thumb -vv something.stl something.png
```

Obviously replace `something` with the name of an stl file you have. It should create a png file with and image of your model. If it fails, can you post the output here?

**Comment by rebeltaz** [comment]
OK... apparently, there is something no supported?

`derek@derek-home:~/downloads$ stl-thumb -vv base.stl base.png
INFO - STL File: base.stl
INFO - Thumbnail File: base.png

INFO - Bounds:
INFO - X: -29.909351, 34.310078
Y: -41.65903, 32.51511
Z: -0.00000758192, 1.0080042

INFO - Center:	Point3 [2.2003632, -4.5719604, 0.5039983]
INFO - Triangles processed:	4842

INFO - GL Version:   Version(Gl, 2, 1)
INFO - GL Version:   2.1 Mesa 18.0.1 - padoka PPA
INFO - GLSL Version: Version(Gl, 1, 2)
INFO - Vendor:       Intel Open Source Technology Center
INFO - Renderer      Mesa DRI Intel(R) Ironlake Mobile 
INFO - Free GPU Mem: None

ERROR - 0:1(10): error: GLSL 1.50 is not supported. Supported versions are: 1.10, 1.20, and 1.00 ES

thread 'main' panicked at 'Compiling shaders', src/lib.rs:105:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.
`

**Comment by unlimitedbacon** [comment]
Fascinating. Can I ask what your system specs are? What kind of GPU do you have and what drivers are you using for it?

**Comment by rebeltaz** [comment]
So.... this is the output of 'lshw -numeric -C display'

  *-display               
       description: VGA compatible controller
       product: Core Processor Integrated Graphics Controller [8086:46]
       vendor: Intel Corporation [8086]
       physical id: 2
       bus info: pci@0000:00:02.0
       version: 02
       width: 64 bits
       clock: 33MHz
       capabilities: msi pm vga_controller bus_master cap_list rom
       configuration: driver=i915 latency=0
       resources: irq:26 memory:d0000000-d03fffff memory:c0000000-cfffffff ioport:5050(size=8)


To my knowledge, I do not have any addition drivers installed that do not come native to Ubuntu.

**Comment by unlimitedbacon** [comment]
It seems that you have somehow managed to install Linux on a potato.

Seriously though, you've got an ancient Intel integrated GPU that only supports the oldest possible version of OpenGL. I thought I was supporting the lowest common denominator of hardware, but evidently I was wrong.

Stl-thumb is not doing anything that should require a newer version, though. I'll try and get the shaders to compile for GLSL 1.20.

Thanks for your help. I'll see what I can do about this.

**Comment by rebeltaz** [comment]
lol... leave it to me to push hardware to the limit :) Thanks dude!

**Comment by unlimitedbacon** [comment]
I just put out [release 0.1.1](https://github.com/unlimitedbacon/stl-thumb/releases/tag/v0.1.1). It should support your GPU now. Please try it out. If it doesn't work, reopen this issue and let me know.

**Comment by rebeltaz** [comment]
Well.... I installed 0.1.1 tonight and rebooted my computer. I'm still not getting previews. If it's because my hardware is too old, that's cool... you don't have to keep trying to support a dinosaur :) I appreciate your help, though. 

![screenshot at 2018-08-17 19 29 52](https://user-images.githubusercontent.com/18725805/44293802-6decfb00-a254-11e8-9f4c-cdf71266c4dc.png)

**Comment by rebeltaz** [comment]
Hmmm... oddly enough, I have found that there are some that it does work on and some that it does not. The "keychain_rocket.stl" does show a preview whereas the "club_bottom.stl" does not.

[Keychain_Rocket.stl.zip](https://github.com/unlimitedbacon/stl-thumb/files/2299072/Keychain_Rocket.stl.zip)
[club_bottom.stl.zip](https://github.com/unlimitedbacon/stl-thumb/files/2299073/club_bottom.stl.zip)

**Comment by unlimitedbacon** [comment]
Both of them work for me. You probably just need to clear your thumbnail cache.
```
rm -rf ~/.cache/thumbnails/fail/*
```
Any file that failed to generate a thumbnail with 0.1.0 is remembered. Nemo will not try to generate thumbnails for those files again unless they are changed or you clear the cache.

**Comment by rebeltaz** [comment]
I did not know that. That did the trick! Thank you :)
