### ISSUE TITLE
memory allocation of 48 bytes failed

### ISSUE THREAD

**Issue by Lino77** [unlimitedbacon/stl-thumb#41]
what does that mean, "memory allocation of 48 bytes failed" preview does not work for me

INFO - STL File: effector.stl
INFO - Thumbnail File: effector.png

INFO - Bounds:
INFO - X: -35.80536, 31.09588
Y: -70.3, -29.256
Z: 3.332, 26.883

INFO - Center:	Point3 [-2.3547392, -49.778, 15.1075]
INFO - Triangles processed:	3672

INFO - GL Version:   Version(Gl, 2, 1)
INFO - GL Version:   2.1 Mesa 21.1.2
INFO - GLSL Version: Version(Gl, 1, 2)
INFO - Vendor:       Mesa/X.org
INFO - Renderer      llvmpipe (LLVM 12.0.0, 256 bits)
INFO - Free GPU Mem: None
INFO - Depth Bits:   None

memory allocation of 48 bytes failed
Abgebrochen (Speicherabzug geschrieben)
My System 

System:    Kernel: 5.10.42-1-MANJARO x86_64 bits: 64 compiler: gcc v: 11.1.0 Desktop: Cinnamon 4.8.6 tk: GTK 3.24.29 vt: 7 
           dm: LightDM 1.30.0 Distro: Manjaro Linux base: Arch Linux 
CPU:       Info: 12-Core model: AMD Ryzen Threadripper 1920X bits: 64 type: MT MCP arch: Zen rev: 1 cache: L2: 6 MiB 
           flags: avx avx2 lm nx pae sse sse2 sse3 sse4_1 sse4_2 sse4a ssse3 svm bogomips: 167712 
           Speed: 3306 MHz min/max: 2200/3500 MHz boost: enabled Core speeds (MHz): 1: 3306 2: 3307 3: 2136 4: 2085 5: 3117 
           6: 3129 7: 1908 8: 1964 9: 1959 10: 1963 11: 1962 12: 2189 13: 1850 14: 2192 15: 2192 16: 2192 17: 2197 18: 1888 
           19: 1888 20: 1889 21: 1885 22: 1886 23: 1888 24: 2188 
Graphics:  Device-1: Advanced Micro Devices [AMD/ATI] Ellesmere [Radeon RX 470/480/570/570X/580/580X/590] vendor: XFX Pine 
           driver: amdgpu v: kernel bus-ID: 43:00.0 chip-ID: 1002:67df class-ID: 0300 
           Display: x11 server: X.Org 1.20.11 driver: loaded: amdgpu,ati unloaded: modesetting alternate: fbdev,vesa 
           resolution: 1: 1920x1080~60Hz 2: 1920x1080~60Hz s-dpi: 96 
           OpenGL: renderer: Radeon RX 580 Series (POLARIS10 DRM 3.40.0 5.10.42-1-MANJARO LLVM 12.0.0) v: 4.6 Mesa 21.1.2 
           direct render: Yes

**Comment by mtorromeo** [comment]
Same issue here, but I realized that it only happens with release builds.
Debug builds do not segfault.

**Comment by planetar** [comment]
Same issue here, INFO - STL File: marks.stl
INFO - Thumbnail File: marks.jpg

INFO - Bounds:
INFO - X: 12.68792, 87.4
Y: 7.369631, 33.68238
Z: -2.5, -2

INFO - Center:  Point3 [50.04396, 20.526005, -2.25]
INFO - Triangles processed:     2514

INFO - GL Version:   Version(Gl, 2, 1)
INFO - GL Version:   2.1 Mesa 21.2.1
INFO - GLSL Version: Version(Gl, 1, 2)
INFO - Vendor:       Mesa/X.org
INFO - Renderer      llvmpipe (LLVM 12.0.1, 256 bits)
INFO - Free GPU Mem: None
INFO - Depth Bits:   None

memory allocation of 48 bytes failed
Abgebrochen (Speicherabzug geschrieben)


Operating System: Arch Linux
KDE Plasma Version: 5.22.5
KDE Frameworks Version: 5.85.0
Qt Version: 5.15.2
Kernel Version: 5.13.13-arch1-1 (64-bit)
Graphics Platform: X11
Processors: 4 × Intel® Core™ i5-4570 CPU @ 3.20GHz
Memory: 31,3 GiB of RAM
Graphics Processor: Mesa DRI Intel® HD Graphics 4600

**Comment by Sergioloid** [comment]
I've the same issue on Manjaro KDE, anyone managed to solve this issue?

**Comment by unlimitedbacon** [comment]
We're working on a fix for this here https://github.com/unlimitedbacon/stl-thumb/pull/44.

**Comment by unlimitedbacon** [comment]
This should be fixed in v0.4.1. Can you confirm?
https://github.com/unlimitedbacon/stl-thumb/releases/tag/v0.4.1

**Comment by planetar** [comment]
It's my pleasure to confirm that with v0.4.1 and arch/kde/dolphin I get previews now for all the stl 
Thanks for all your efforts!

**Comment by unlimitedbacon** [comment]
Excellent. Closing this issue. Feel free to reopen if this crops up again.
