### ISSUE TITLE
Problem Previews on Xyplorer

### ISSUE THREAD

**Issue by boromyr** [unlimitedbacon/stl-thumb#43]
Hi, I can't see the previews in Xyplorer, an alternative file manager at Windows 10 Explorer. I added the clsid of STL-thumb to Xyplorer, as I did for other types of extension, but without success. The previews are only loaded if you create first with Explorer.exe.
Windows 10 x64
Xyplorer 21.90 X32 (not available at 64bit).

**Comment by unlimitedbacon** [comment]
> Xyplorer 21.90 X32 (not available at 64bit).

That may have something to do with it. Stl-thumb is 64 bit only. Why doesn't Xyplorer support 64 bit?

**Comment by boromyr** [comment]
I read that it is written in Visual Basic 6, which does not have a 64bit compiler.

**Comment by unlimitedbacon** [comment]
Visual Basic? wtf?

Sorry. Not going to try to support either VB or 32 bit. Both are very obsolete.
