### ISSUE TITLE
Trying this out with xfce - no joy yet

### ISSUE THREAD

**Issue by smartavionics** [unlimitedbacon/stl-thumb#5]
Hi,
This looks great and I am trying it out on Ubuntu 16.04.4 with xfce. I installed your deb and the command line program works fine. The file manager says the stl files are type model/stl but I am not getting any thumbnails. I restarted Thunar. Any idea what I can check next?

Thanks.

**Comment by smartavionics** [comment]
I installed another file manager, PCmanFM and that has created the thumbnails and now Thunar can see those. I'll close this issue as it just looks like Thunar has a problem.

**Comment by unlimitedbacon** [comment]
1. Make sure that you have `tumbler` installed as well. Thunar requires it for making thumbnails.
2. In your Thunar preferences, make sure that "Show thumbnails:" is not set to "Never".

**Comment by smartavionics** [comment]
Thanks for the help, both of those things are true. It doesn't matter now I can use PCmanFM. Cheers!
