### ISSUE TITLE
Add Command Line Support

### ISSUE THREAD

**Issue by J0nnyI** [unlimitedbacon/stl-thumb#53]
I am currently working on a 3d file management software and am looking for an performant way to create thumbnails for 3d files, as doing this with C# is not feasible.
Are you able to estimate the effort it would take to expand the project to support thumbnail generation by command line? I don't need anything fancy, just a  object path and a thumbnail path as parameter and it should generate the thumbnail at the given location.

Of course I am willing to learn Rust (never done it before) to implement the feature myself and credit your project in case this is feasible.

**Comment by unlimitedbacon** [comment]
Uhm... It already has that. Have you looked at the bottom of the README? This is exactly how thumbnail generators are invoked on Linux.

**Comment by J0nnyI** [comment]
Great, thank you and sorry for overlooking that part of your Readme.

Tyler Anderson ***@***.***> schrieb am Mo., 31. Jan. 2022,
09:18:
