### ISSUE TITLE
No shaders in default?

### ISSUE THREAD

**Issue by LeandroMarceddu** [unlimitedbacon/stl-thumb#59]
Hey

By default (in Windows 11), running a command like this:

`./stl-thumb.exe D:\Projects\PlaterFlow\output\plater_main_1.stl plater.png`

Returns the following plater.png: 
![plater](https://user-images.githubusercontent.com/227830/170455996-895d0b8c-8b6f-4e84-aa15-bb724428a410.png)

Is this normal/correct? If not, what's going wrong here?

**Comment by LeandroMarceddu** [comment]
You seem to be on to something, I've tried using the tool do to individual STLs and this works flawless.

Opening MeshLab to view which are the normals that are inverted revealed none though;
![image](https://user-images.githubusercontent.com/227830/170545856-52752054-930a-4a05-a649-e02d79db20a2.png)
(they should be indicated in black)
Below is a view with the normals enabled and this seems to be correct.
![image](https://user-images.githubusercontent.com/227830/170546476-4965498c-5486-4e40-ae65-74db5635ef75.png)


I've included the STL which has been giving me these issues below.
[plater_main_1.zip](https://github.com/unlimitedbacon/stl-thumb/files/8781038/plater_main_1.zip)

All the regular STLs (e.g the individual ones) seem to be working and rendering okay, it's just that when they get grouped together and saved into a single STL this seems to be breaking it.

**Comment by LeandroMarceddu** [comment]
So, I took it to Netfabb. 

Unaltered it keeps giving me the same view as the first post. After performing the 'standard repair' by the (very old) netfabb basic, it renders to the proper view.

Analysing both files gives me this:
Old: 
![image](https://user-images.githubusercontent.com/227830/170547788-c55aa970-08db-4057-b93c-e1ddd5a4f7c5.png)
Repaired STL:
![image](https://user-images.githubusercontent.com/227830/170547999-60ae2a84-7940-416a-a104-19180e644ad4.png)
Other than edge length I see no noteworthy alterations. 

Tried looking into what alterations the 'repair' function brings but have not found any clue whatsoever. If you have any ideas. 

Attached repaired STL file. 
[plater_main_1 (repaired).zip](https://github.com/unlimitedbacon/stl-thumb/files/8781136/plater_main_1.repaired.zip)

**Comment by unlimitedbacon** [comment]
Oh look, someone is printing a Voron.

Anyways I had a look at your file and I know what is going on. STL files optionally provide the normal vector for each face of the model (https://en.wikipedia.org/wiki/STL_(file_format)#The_facet_normal). Many programs simply ignore the normal vector if it is given in the file and calculate it on their own. For the sake of speed, stl-thumb uses the normals from the file if they are given and only calculates them if they are not.

Your file has the same normal vector for every face, `[1.0, 0.0, 0.0]`, so each face receives the same shading. Whatever is generating your file should either provide valid normals or just use `[0.0, 0.0, 0.0]` to indicate that the receiving program should calculate them.

**Comment by LeandroMarceddu** [comment]
Plater is on the generating end of the files so instead I'll look into forcing stl-thumb to calculate the normals :) 

Thanks a lot!
