### ISSUE TITLE
fails to install under Win 10 with AVG

### ISSUE THREAD

**Issue by jon-bondy** [unlimitedbacon/stl-thumb#6]
AVG worries about the installer, then says things are OK, then worries about a new EXE that the installer spawns, then says things are OK, and then the installation fails.  I could find no way to add a comment to the thread about this under 3D printing.  Google Plus remains unfathomable to me.

**Comment by unlimitedbacon** [comment]
Does AVG provide any details about what it is worried about? What does the installer say when it fails? Please provide as much specific information as you can.

The only thing that I think it would have a problem with is that the installer is unsigned.
