### ISSUE TITLE
KDE/Dolphin doesn't support thumbnailers API

### ISSUE THREAD

**Issue by mrvanes** [unlimitedbacon/stl-thumb#7]
KDE/Dolphin has it's own ThumbCreator API :(
https://bbs.archlinux.org/viewtopic.php?pid=1556175#p1556175
https://api.kde.org/frameworks/kio/html/classThumbCreator.html

**Comment by unlimitedbacon** [comment]
Ugh. This means its going to be almost as much of a pain as Windows was. Rust will not interface directly with a C++ API so some kind of wrapper is going to be required.

**Comment by unlimitedbacon** [comment]
[Keneric](https://store.kde.org/p/1080815/) might be a solution.

**Comment by fandres** [comment]
Any progress? It's a shame that this is not something like this for KDE: /

**Comment by unlimitedbacon** [comment]
I have been investigating restructuring stl-thumb as a library instead of just being an executable. This would use Rust's FFI to allow us to call stl-thumb from C or C++ code. It would make a KDE plugin possible and also make the Windows shell extension a lot less hacky.

**Comment by Marte2007** [comment]
Any news on this?
It's 2021, Keneric is no more, and there's still no STL thumbnailer for KDE...

**Comment by unlimitedbacon** [comment]
I've been able to make some progress on a KDE plugin. It's somewhat functional, but still needs work.

**Comment by unlimitedbacon** [comment]
[stl-thumb 0.40](https://github.com/unlimitedbacon/stl-thumb/releases/tag/v0.4.0) now supports KDE.
