### ISSUE TITLE
Doesn't work on Ubuntu 18.04

### ISSUE THREAD

**Issue by Goury** [unlimitedbacon/stl-thumb#9]
Because library libOSMesa.so that this thing uses is not there, libosmesa6-dev should be added as a dependency.

**Comment by gsedej** [comment]
Same here. Nautilus output says
`Unable to create headless GL context. Trying hidden window instead. Reason: NoBackendAvailable(LoadingError("LibraryNotFound { descr: \"libOSMesa.so: cannot open shared object file: No such file or directory\" }"))`

The `libosmesa6` is installed (also `libosmesa6-dev`)

**Comment by unlimitedbacon** [comment]
Weird. I don't know why `libosmesa6` isn't enough. Dependency added for `libosmesa6-dev`.

**Comment by gsedej** [comment]
Despite my issue about output, the thumbnailer works for some STL files. Those that don't work (no thumbnail displayed) are usually broken (e.g. Slic3r can't slice it correctly)

@Goury Did you tried different stl files? Try just exporting default cube in blender as stl.

**Comment by Goury** [comment]
@gsedej 
I don't have broken STL files.
And this was not the case.
